package Database.Entities;

import Utilities.TimeUtilities;
import java.time.ZonedDateTime;

public class Appointment {
   private int appointmentID;
   private int customerId;
   private int userId;
   private String title;
   private String description;
   private String location;
   private String type;
   private ZonedDateTime start;
   private ZonedDateTime end;
   private ZonedDateTime createDate;
   private String formattedStartString = "";
   private String formattedEndString = "";
   private String formattedCreateDateString = "";
   private String createdBy;
   private ZonedDateTime lastUpdate;
   private String lastUpdatedBy;
   private int contactId;


   /** Constructor method with required parameters.
    * @param appointmentID An auto-generated by the database int, designating this unique appointment, that is disabled for any user.
    * @param title String that may be adjusted by any user, designating the title of this appointment.
    * @param description String that may be adjusted by any user, containing a short description of the appointment.
    * @param location String that may be adjusted by any user, designating the location address of the appointment.
    * @param type String that may be adjusted by any user, designating the type of appointment.
    * @param start A ZonedDateTime that may be adjusted by any user, designating the beginning of the appointment.
    * @param end A ZonedDateTime that may be adjusted by any user, designating the end of the appointment.
    * @param createDate A ZonedDateTime that may be adjusted by any user, designating the date and time it is created.
    * @param createdBy A String, designating the User creating this appointment, that may be adjusted by any user.
    * @param lastUpdate An Instant, designating the most recent moment a User changed info, that may be adjusted by any user.
    * @param lastUpdatedBy String, designating the last User to change info, that may be adjusted by any user.
    * @param customerId Int, designating the customer's unique Id, that may be adjusted by any user.
    * @param userId Int, designating the User related to this appointment, that may be adjusted by any user.
    * @param contactId Int, designating who made to contact, that may be adjusted by any user.
    */
   public Appointment(int appointmentID, String title, String description, String location, String type,
                      ZonedDateTime start, ZonedDateTime end, ZonedDateTime createDate, String createdBy,
                      ZonedDateTime lastUpdate, String lastUpdatedBy, int customerId, int userId, int contactId) {
      this.appointmentID = appointmentID;
      this.title = title;
      this.description = description;
      this.location = location;
      this.type = type;
      this.start = start;
      this.end = end;
      this.createDate = createDate;
      this.createdBy = createdBy;
      this.lastUpdate = lastUpdate;
      this.lastUpdatedBy = lastUpdatedBy;
      this.customerId = customerId;
      this.userId = userId;
      this.contactId = contactId;
      setFormattedCreateDateString(TimeUtilities.formatZDTToString(createDate));
      setFormattedEndString(TimeUtilities.formatZDTToString(end));
      setFormattedStartString(TimeUtilities.formatZDTToString(start));
   }
   
   
   /** Getter for customerId created by database's auto-increment.
    * @return Returns int customerId.
    */
   public int getCustomerId() {
      return customerId;
   }
   
   /** Setter for int customerId.
    * @param customerId Input int to be new customerId value.
    */
   public void setCustomerId(int customerId) {
      this.customerId = customerId;
   }
   
   /** Getter for Title String.
    * @return Returns String title.
    */
   public String getTitle() {
      return title;
   }
   
   /** Setter for String title.
    * @param title Input new String value for title.
    */
   public void setTitle(String title) {
      this.title = title;
   }
   
   /** Getter for appointmentID.
    * @return Returns int appointmentID.
    */
   public int getAppointmentID() {
      return appointmentID;
   }
   
   
   /** Getter for createDate.
    * @return Returns ZonedDateTime of createDate.
    */
   public ZonedDateTime getCreateDate() {
      return createDate;
   }
   
   /** Setter for createDate.
    * @param createDate Input ZonedDateTime to be new createDate value.
    */
   public void setCreateDate(ZonedDateTime createDate) {
      this.createDate = createDate;
   }
   
   /** Getter for createdBy String.
    * @return Returns String of createdBy value.
    */
   public String getCreatedBy() {
      return createdBy;
   }
   
   /** Setter for createdBy String.
    * @param createdBy Input String to be new value.
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }
   
   /** Getter for LastUpdate
    * @return Returns ZonedDateTime lastUpdate
    */
   public ZonedDateTime getLastUpdate() {
      return lastUpdate;
   }
   
   /** Setter for ZonedDateTime lastUpdate.
    * @param lastUpdate Input ZonedDateTime to be new lastUpdate value.
    */
   public void setLastUpdate(ZonedDateTime lastUpdate) {
      this.lastUpdate = lastUpdate;
   }
   
   /** Getter for String lastUpdatedBy, which is to be a User's name.
    * @return the String value of lastUpdatedBy.
    */
   public String getLastUpdatedBy() {
      return lastUpdatedBy;
   }
   
   /** Setter for String lastUpdatedBy.
    * @param lastUpdatedBy Input String to be new value of lastUpdatedBy.
    */
   public void setLastUpdatedBy(String lastUpdatedBy) {
      this.lastUpdatedBy = lastUpdatedBy;
   }
   
   /** Getter for String description.
    * @return the String description.
    */
   public String getDescription() {
      return description;
   }
   
   /** Setter for String description.
    * @param description Input String to be new value of description.
    */
   public void setDescription(String description) {
      this.description = description;
   }
   
   /** Getter for the User's ID.
    * @return the int value of userId.
    */
   public int getUserId() {
      return userId;
   }
   
   /** Setter for the User's ID.
    * @param userId Input int to be new value of the User's ID.
    */
   public void setUserId(int userId) {
      this.userId = userId;
   }

   /**
    * Getter for the String holding the type of Appointment.
    * @return the String value of type.
    */
   public String getType() {
      return type;
   }
   
   /**
    * Setter for the Appointment type String value.
    * @param type Input String to be new type value.
    */
   public void setType(String type) {
      this.type = type;
   }
   
   /**
    * Getter for String containing Appointment's location.
    * @return Returns String value of Appointment's location.
    */
   public String getLocation() {
      return location;
   }
   
   /**
    * Setter for Appointment location.
    * @param location Input String to be new location value.
    */
   public void setLocation(String location) {
      this.location = location;
   }
   
   
   /**
    * Getter for the ZonedDateTime for the start of this Appointment.
    * @return Returns the ZonedDateTime of Appointment start.
    */
   public ZonedDateTime getStartZonedDateTime() {
      return start;
   }
   
   /**
    * Setter for Appointment's start date+time.
    * @param start Input ZonedDateTime to be new value of Appointment's start.
    */
   public void setStartZonedDateTime(ZonedDateTime start) {
      this.start = start;
   }
   
   /**
    * Getter for Appointment's end date+time.
    * @return Returns the ZonedDateTime of Appointment's end.
    */
   public ZonedDateTime getEndZonedDateTime() {
      return end;
   }
   
   /**
    * Setter for Appointment's end date+time.
    * @param end Returns the ZonedDateTime of Appointment's end.
    */
   public void setEndZonedDateTime(ZonedDateTime end) {
      this.end = end;
   }

   /**
    * Method is the getter for Contact_ID from an Appointment Object.
    * @return The contact's ID as an int.
    */
   public int getContactId() {
      return contactId;
   }

   /**
    * Method is the setter for Contact_ID from an Appointment Object.
    * @param contactId The new int to become the new Contact_ID.
    */
   public void setContactId(int contactId) {
      this.contactId = contactId;
   }


   /**
    * Getter for the formatted String value of Appointment's start.
    * @return Returns the String containing this Appointment's start.
    */
   public String getFormattedStartString() {
      return formattedStartString;
   }

   /**
    * Setter for the formatted String value of Appointment's start.
    * @param formattedStartString Input String to be new Appointment start value.
    */
   public void setFormattedStartString(String formattedStartString) {
      this.formattedStartString = formattedStartString;
   }

   /**
    * Getter for formatted String value of Appointment's end.
    * @return Returns String containing Appointment's formatted start.
    */
   public String getFormattedEndString() {
      return formattedEndString;
   }

   /** Setter for formatted String value of Appointment's end.
    * @param formattedEndString Input String to be new value of Appointment's formatted end date+time.
    */
   public void setFormattedEndString(String formattedEndString) {
      this.formattedEndString = formattedEndString;
   }

   /**
    * Getter for formatted String of Appointment's creation date.
    * @return Returns the pre-formatted String of Appointment's end date+time.
    */
   public String getFormattedCreateDateString() {
      return formattedCreateDateString;
   }

   /**
    * Setter for formatted String of Appointment's end.
    * @param formattedCreateDateString Input String to be new value of Appointment's formatted-String creation date.
    */
   public void setFormattedCreateDateString(String formattedCreateDateString) {
      this.formattedCreateDateString = formattedCreateDateString;
   }
}


