package Database.Entities;

import java.time.Instant;
import java.time.ZonedDateTime;

public class Customer {

   private String lastUpdatedBy;
   private ZonedDateTime lastUpdate;
   private String createdBy;
   private ZonedDateTime createDate;
   private String address;
   private String customerName;
   private int customerId;
   private int firstDivisionId;
   private String postalCode;
   private String phoneNumber;

   /** Default Constructor for Customer.class
    * @param customerId Input int is value auto-generated by database to be unique, primary key for this Customer.
    * @param customerName Input String is the value of the name for this Customer, first and last separated by a space.
    * @param address Input String which holds the value of the Customer's street address.
    * @param postalCode Input String that holds the value of the Customer's postal code.
    * @param phoneNumber Input String that holds the value of this Customer's phone number.
    * @param createDate Input ZonedDateTime that holds the value of this Customer's initial creation date and time.
    * @param createdBy Input String that holds the value of the Username that initially created this Customer.
    * @param lastUpdate Input Instant that holds the time value of this Customer's latest update.
    * @param lastUpdatedBy Input String that holds the value of the Username that committed the latest update to this Customer.
    * @param firstDivisionId Input int that holds the Division_ID corresponding to this Customer.
    */
   public Customer(int customerId, String customerName, String address, String postalCode, String phoneNumber,
                   ZonedDateTime createDate, String createdBy, ZonedDateTime lastUpdate, String lastUpdatedBy, int firstDivisionId) {
      this.customerId = customerId;
      this.firstDivisionId = firstDivisionId;
      this.customerName = customerName;
      this.address = address;
      this.postalCode = postalCode;
      this.phoneNumber = phoneNumber;
      this.createDate = createDate;
      this.createdBy = createdBy;
      this.lastUpdate = lastUpdate;
      this.lastUpdatedBy = lastUpdatedBy;
   }

   /** Getter for customers column Customer_ID
    * @return Customer_ID as int
    */
   public int getCustomerId() {
      return customerId;
   }

   /** Setter for customers column Customer_ID
    * @param customerId int Customer_ID
    */
   public void setCustomerId(int customerId) {
      this.customerId = customerId;
   }

   /** Getter for the customers column Customer_Name
    * @return String of Customer_Name
    */
   public String getCustomerName() {
      return customerName;
   }

   /** Setter for customers column Customer_Name
    * @param customerName String to be set as Customer_Name
    */
   public void setCustomerName(String customerName) {
      this.customerName = customerName;
   }

   /** Getter for customers column Address
    * @return String address
    */
   public String getAddress() {
      return address;
   }

   /** Setter for customers Address
    * @param address String to be set as Address
    */
   public void setAddress(String address) {
      this.address = address;
   }

   /** Getter for customers Create_Date
    * @return ZonedDateTime is converted from database's DateTime - java equivalent is LocalDateTime
    */
   public ZonedDateTime getCreateDate() {
      return createDate;
   }

   /** Setter for customers Create_Date
    * @param createDate Requires a ZonedDateTime to replace the originally converted ZoneDateTime
    */
   public void setCreateDate(ZonedDateTime createDate) {
      this.createDate = createDate;
   }

   /** Getter for customers Created_By column
    * @return Returns String of user's name that created this record
    */
   public String getCreatedBy() {
      return createdBy;
   }

   /** Setter for customers Created_By column
    * @param createdBy Requires input string of the creating user's name
    */
   public void setCreatedBy(String createdBy) {
      this.createdBy = createdBy;
   }

   /** Getter for customers column Last_Update
    * @return Returns an Instant when the last update occured.
    */
   public ZonedDateTime getLastUpdate() {
      return lastUpdate;
   }

   /** Setter for customers column Last_Update
    * @param lastUpdate Requires input of a new Instant to replace previous.
    */
   public void setLastUpdate(ZonedDateTime lastUpdate) {
      this.lastUpdate = lastUpdate;
   }

   /** Getter for customers column Last_Updated_By
    * @return Returns a string of the user's name to perform the last update on this record
    */
   public String getLastUpdatedBy() {
      return lastUpdatedBy;
   }

   /** Setter for Last_Update_By in customers
    * @param lastUpdatedBy Required input is String to be new user's name to perform last update
    */
   public void setLastUpdatedBy(String lastUpdatedBy) {
      this.lastUpdatedBy = lastUpdatedBy;
   }

   /** Getter for customers column Division_ID
    * @return Returns an int of the Division_ID
    */
   public int getFirstDivisionId() {
      return firstDivisionId;
   }

   /** Setter for customers Division_ID
    * @param firstDivisionId Require int input of new Division_ID
    */
   public void setFirstDivisionId(int firstDivisionId) {
      this.firstDivisionId = firstDivisionId;
   }


   /** Getter for customers Postal_Code
    * @return Returns a String of the customer's Postal_Code
    */
   public String getPostalCode() {
      return postalCode;
   }

   /** Setter for customers Postal_Code
    * @param postalCode Input parameter must be a String to be new Postal_Code
    */
   public void setPostalCode(String postalCode) {
      this.postalCode = postalCode;
   }

   /** Getter for customers Phone (number)
    * @return Returns a customers Phone (number) as a String
    */
   public String getPhoneNumber() {
      return phoneNumber;
   }

   /** Setter for customers Phone (number)
    * @param phoneNumber Required input parameter String to be new Phone (number)
    */
   public void setPhoneNumber(String phoneNumber) {
      this.phoneNumber = phoneNumber;
   }
}
